### ISSUE TITLE
チーム辞書を作成する

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/my_dictionary#5]
## やりたいこと
1. チーム内で閲覧、共同編集ができる辞書を自分の辞書の他に作成したい。
2. チーム辞書を作成したら、チーム名とパスワード入力で他のユーザーも入ることができる。
3. 入っているメンバーを確認できる。
(チャットルームを作成する工程と似ているのかも。ただチーム内でできることは辞書の管理のみで、チャットはできない。）
## 試したこと
deviseを他のteamモデルにつけて作成した(エラーが解消できなくなったので削除してしまったが）
## 問題点
userですでにdeviseを導入していることもあり、メールアドレスでのログインを外すことができない。userモデルのdevise.rbとteamモデルのdevise.rbを分けたいのだが、できていない。

**Comment by ms2sato** [comment]
@shuma1020 チーム辞書の仕様として以下の方がわかりやすいと思いますが、上記の仕様へのこだわりがあったりしますか？

Deviseを利用しようとすること自体がちょっと微妙な仕様にも見えているので、その点を考えた方が良さそうです。ユーザーアカウント管理にDeviseを使うのは一般的ですが上記のような用途はあまりやらないかなと。

チームを作成した人が、誰が入れるかも設定できて（例えばメールアドレスなどを利用してフィルタ。厳密にはこれだけだと課題もありますが）、特にチームにパスワードを設定しないのが一般的なサービスの仕様に近いと思います。

**Comment by shuma1020** [comment]
@ms2sato 
deviseの導入は微妙だなとやっていて感じていたので、そのように仰っていただいてよかったです
。ただアイデアの引き出しにdeviseしか今実装したい機能を実現できるであろうものがなかったためdeviseでまず進めていました。

ググり方として「チャットルーム作成　rails」「管理　権限　付与 rails」とか色々やっているのですが、自分の実現したい機能は世に言うどれに当てはまるのかを探すのが意外と苦戦しています。

**Comment by ms2sato** [comment]
@shuma1020 今やることって、既に @shuma1020 が持っている知識を組み合わせてできることではないですかね？ググって何かを写してやるような感じでは無いですよ。

これは「小さな機能を組み合わせて仕組みを作る」というプログラミングの醍醐味の部分なので、どうできるか考える方が良いと思います。やりたいことをプログラミングの仕組みの言葉に直して、どうできるか組み合わせる事をすると良いでしょう。

**Comment by ms2sato** [comment]
@shuma1020 そもそも、のところをできないといけないのですが、ちなみに私がこれから書くところも自分なりに考え持って先に提示欲しい内容です。

### データ構造について
こちらは下の方で「TeamモデルとPostも１対多の関係」というところで書いています。まずどういう単位で情報を保存するか決めなければ進みません。

### アクセスの拒否について
既にアクセスの拒否をする方法は @shuma1020 が 提案できる気がするのですが、フォロー必要でしょうか。

- リクエストされた時に共通の処理を挟み込む方法
  - もう結構やっている気がします。管理者かどうかチェックするとかでもやっていますよね。
- アクセスが許可されているかどうかを判断する方法
  - 「Userモデルのroleではなく、メールアドレスによってどのように判断するか」この疑問の答えになってしまうので書きたくないですが、Userはメールアドレスを持ってて、許可されるメールアドレスのリストがあれば、判断できそうですが難しいでしょうか。

> TeamモデルとPostも１対多の関係

これでもシンプルで私は良いと思いますよ。複雑な仕様がない場合、私が作るならこうかな。
Postは作成したユーザーに関連し、もしもTeam辞書ならTeamに「も」属する感じ。

> cancancan

今はこれ使わずにやりましょ。多分これを使って実現できてもなぜできたのかわからないと思うので。

**Comment by shuma1020** [comment]
@ms2sato こちらの木曜日のアドバイスをいただいてから、Pull Requestの方でやりとりしていたため、こちらはやりとりIssue更新していませんでした。申し訳ございません。
